# Generated by Django 5.1.5 on 2025-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('user_agent', models.TextField(verbose_name='디바이스 정보')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='방문 시간')),
            ],
        ),
    ]
