# Generated by Django 5.1.5 on 2025-01-28 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='행위 시간')),
                ('action_type', models.CharField(max_length=50, verbose_name='행위 유형')),
                ('file_names', models.TextField(verbose_name='파일 이름들')),
                ('user_agent', models.TextField(blank=True, verbose_name='디바이스 정보')),
            ],
        ),
    ]
