# Generated by Django 5.1.5 on 2025-01-30 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_useractionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='browser',
            field=models.CharField(blank=True, max_length=100, verbose_name='브라우저'),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='운영체제'),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='세션 ID'),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='browser',
            field=models.CharField(blank=True, max_length=100, verbose_name='브라우저'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='접속 도시'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='접속 국가'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='http_method',
            field=models.CharField(default='GET', max_length=10, verbose_name='요청 메서드'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='운영체제'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='referer_url',
            field=models.URLField(blank=True, null=True, verbose_name='리퍼러 URL'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='request_url',
            field=models.TextField(default='', verbose_name='요청한 URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='세션 ID'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
